### ISSUE TITLE
Allow admins to approve/reject posts

### ISSUE THREAD

**Issue by KanavKG** [GTBitsOfGood/Liv2BGirl#127]
### Implementation

**MVP:**

- If a user has submitted a post, the Admin should receive a notification on their notifications page.
- Clicking on the notification allows them to view the post and caption.
- They have a approve or reject button and can click either
- If they click 'approve', post becomes visible to all
- If they click 'reject' post is destroyed

**Implementation details**
- Create a page where posts that need to be approved would show up
- Query the database and get all posts that are yet to be approved
- Create a approve and reject button for every post
- If approved, change post's approved flag to true

**Comment by hdemusg** [comment]
I'll go ahead and put myself on this one, because I'm already working with admin functionalities for my Sprint 1 task.

**Comment by KanavKG** [comment]
Sounds good!
